"""Builds the two resource files and the class that reads them, from one list of strings.

Run it from the repository root after editing tools/strings.json:

    python tools/strings.py

The class goes into the source tree rather than being generated during the build, because WPF
compiles XAML in a second pass through a temporary project that cannot see files the first pass
made. That failure looks like "the name Strings does not exist" and takes a while to understand.
"""

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

RESX_HEAD = '''<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence><xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" /></xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
'''

CLASS_HEAD = '''// <auto-generated>
//     Made by tools/strings.py from tools/strings.json. Do not edit by hand: run the script.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace Aiko.App;

/// Every word Aiko says, in the language the user chose. One property per string, so a key that
/// does not exist is a build error and not a blank label somebody finds months later.
public static class Strings
{
    private static readonly ResourceManager Resources =
        new("Aiko.App.Strings", typeof(Strings).Assembly);

    /// Set at startup and again when the language changes.
    public static CultureInfo? Culture { get; set; }

    private static string Get(string key) => Resources.GetString(key, Culture) ?? key;
'''


def escape(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def write_resx(path, pairs):
    parts = [RESX_HEAD]
    for key, value in pairs:
        parts.append(
            '  <data name="%s" xml:space="preserve">\n    <value>%s</value>\n  </data>\n'
            % (key, escape(value)))
    parts.append("</root>\n")
    io.open(path, "w", encoding="utf-8", newline="\n").write("".join(parts))


def write_class(path, pairs):
    parts = [CLASS_HEAD]
    for key, value in pairs:
        summary = value.replace("\n", " ")
        if len(summary) > 92:
            summary = summary[:89] + "..."
        parts.append('\n    /// %s\n    public static string %s => Get("%s");\n'
                     % (escape(summary), key, key))
    parts.append("}\n")
    io.open(path, "w", encoding="utf-8", newline="\n").write("".join(parts))


def main():
    data = json.load(io.open(os.path.join(HERE, "strings.json"), encoding="utf-8"))
    keys = [k for k, _ in data]
    if len(keys) != len(set(keys)):
        raise SystemExit("two entries share a key")

    app = os.path.join(ROOT, "src", "Aiko.App")
    write_resx(os.path.join(app, "Strings.resx"), [(k, v[0]) for k, v in data])
    write_resx(os.path.join(app, "Strings.ru.resx"), [(k, v[1]) for k, v in data])
    write_class(os.path.join(app, "Strings.Designer.cs"), [(k, v[0]) for k, v in data])
    print("strings: %d" % len(data))


if __name__ == "__main__":
    main()
