"""Builds the resource files and the classes that read them, from one list of strings.

Run it from the repository root after editing tools/strings.json:

    python tools/strings.py

The class goes into the source tree rather than being generated during the build, because WPF
compiles XAML in a second pass through a temporary project that cannot see files the first pass
made. That failure looks like "the name Strings does not exist" and takes a while to understand.

The macOS app reads the same list from mac/Sources/AikoKit/Strings.swift, written here too. Both
apps say the same words because both are made from this one file; a table typed a second time by
hand would drift apart in a week.
"""

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

RESX_HEAD = '''<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence><xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" /></xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
'''

CLASS_HEAD = '''// <auto-generated>
//     Made by tools/strings.py from tools/strings.json. Do not edit by hand: run the script.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace Aiko.App;

/// Every word Aiko says, in the language the user chose. One property per string, so a key that
/// does not exist is a build error and not a blank label somebody finds months later.
public static class Strings
{
    private static readonly ResourceManager Resources =
        new("Aiko.App.Strings", typeof(Strings).Assembly);

    /// Set at startup and again when the language changes.
    public static CultureInfo? Culture { get; set; }

    private static string Get(string key) => Resources.GetString(key, Culture) ?? key;
'''


def escape(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def write_resx(path, pairs):
    parts = [RESX_HEAD]
    for key, value in pairs:
        parts.append(
            '  <data name="%s" xml:space="preserve">\n    <value>%s</value>\n  </data>\n'
            % (key, escape(value)))
    parts.append("</root>\n")
    io.open(path, "w", encoding="utf-8", newline="\n").write("".join(parts))


def write_class(path, pairs):
    parts = [CLASS_HEAD]
    for key, value in pairs:
        summary = value.replace("\n", " ")
        if len(summary) > 92:
            summary = summary[:89] + "..."
        parts.append('\n    /// %s\n    public static string %s => Get("%s");\n'
                     % (escape(summary), key, key))
    parts.append("}\n")
    io.open(path, "w", encoding="utf-8", newline="\n").write("".join(parts))


SWIFT_HEAD = '''// Made by tools/strings.py from tools/strings.json. Do not edit by hand: run the script.

import Foundation

/// The two languages Aiko has words for. The setting also has "follow the system", which is
/// turned into one of these before the app asks for a word.
public enum StringLanguage: Sendable, Equatable {
    case english
    case russian
}

/// Every word Aiko says, in the language the user chose. One property per string, so a key that
/// does not exist is a build error and not a blank label somebody finds months later.
///
/// The table is the twin of Strings.resx and Strings.ru.resx on Windows.
public enum Strings {
    /// Set at startup and again when the language changes. The lock is there because the bridge
    /// and the app may ask from another thread, not because the value changes often.
    nonisolated(unsafe) private static var chosen = StringLanguage.english
    private static let lock = NSLock()

    public static var language: StringLanguage {
        get { lock.lock(); defer { lock.unlock() }; return chosen }
        set { lock.lock(); defer { lock.unlock() }; chosen = newValue }
    }

    public static func get(_ key: String) -> String {
        guard let pair = table[key] else { return key }
        return language == .russian ? pair.russian : pair.english
    }

    /// Fills {0}, {1} and so on, the way string.Format does on Windows. The texts are shared, so
    /// the placeholders have to be read the same way on both systems.
    public static func format(_ text: String, _ arguments: CustomStringConvertible...) -> String {
        var filled = text
        for (index, argument) in arguments.enumerated() {
            filled = filled.replacingOccurrences(of: "{\\(index)}", with: argument.description)
        }
        return filled
    }

    public static let table: [String: (english: String, russian: String)] = [
'''


def swift_name(key):
    name = key[0].lower() + key[1:]
    keywords = {
        "as", "associatedtype", "break", "case", "catch", "class", "continue", "default", "defer",
        "deinit", "do", "else", "enum", "extension", "fallthrough", "false", "fileprivate", "for",
        "func", "guard", "if", "import", "in", "init", "inout", "internal", "is", "let", "nil",
        "operator", "private", "protocol", "public", "repeat", "rethrows", "return", "self",
        "static", "struct", "subscript", "super", "switch", "throw", "throws", "true", "try",
        "typealias", "var", "where", "while",
    }
    return "`%s`" % name if name in keywords else name


def swift_text(text):
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_swift(path, data):
    parts = [SWIFT_HEAD]
    for key, value in data:
        parts.append('        "%s": ("%s", "%s"),\n'
                     % (key, swift_text(value[0]), swift_text(value[1])))
    parts.append("    ]\n")

    for key, value in data:
        summary = value[0].replace("\n", " ")
        if len(summary) > 92:
            summary = summary[:89] + "..."
        # Spelled with the type name because a bare get( reads as the start of a getter.
        parts.append('\n    /// %s\n    public static var %s: String { Strings.get("%s") }\n'
                     % (summary, swift_name(key), key))
    parts.append("}\n")
    io.open(path, "w", encoding="utf-8", newline="\n").write("".join(parts))


def main():
    data = json.load(io.open(os.path.join(HERE, "strings.json"), encoding="utf-8"))
    keys = [k for k, _ in data]
    if len(keys) != len(set(keys)):
        raise SystemExit("two entries share a key")

    app = os.path.join(ROOT, "src", "Aiko.App")
    write_resx(os.path.join(app, "Strings.resx"), [(k, v[0]) for k, v in data])
    write_resx(os.path.join(app, "Strings.ru.resx"), [(k, v[1]) for k, v in data])
    write_class(os.path.join(app, "Strings.Designer.cs"), [(k, v[0]) for k, v in data])
    write_swift(os.path.join(ROOT, "mac", "Sources", "AikoKit", "Strings.swift"), data)
    print("strings: %d" % len(data))


if __name__ == "__main__":
    main()
