// <auto-generated>
//     Made by tools/strings.py from tools/strings.json. Do not edit by hand: run the script.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace Aiko.App;

/// Every word Aiko says, in the language the user chose. One property per string, so a key that
/// does not exist is a build error and not a blank label somebody finds months later.
public static class Strings
{
    private static readonly ResourceManager Resources =
        new("Aiko.App.Strings", typeof(Strings).Assembly);

    /// Set at startup and again when the language changes.
    public static CultureInfo? Culture { get; set; }

    private static string Get(string key) => Resources.GetString(key, Culture) ?? key;

    /// Session · 5 hours
    public static string CardSession => Get("CardSession");

    /// Week
    public static string CardWeek => Get("CardWeek");

    /// {0} · week
    public static string CardModelWeek => Get("CardModelWeek");

    /// {0}% used
    public static string CardPercentUsed => Get("CardPercentUsed");

    /// resets in {0}
    public static string CardResets => Get("CardResets");

    /// just reset
    public static string CardJustReset => Get("CardJustReset");

    /// lasts until reset
    public static string CardLastsUntilReset => Get("CardLastsUntilReset");

    /// ~{0} at this pace
    public static string CardAtThisPace => Get("CardAtThisPace");

    /// running low
    public static string CardToneCaution => Get("CardToneCaution");

    /// almost gone
    public static string CardToneCritical => Get("CardToneCritical");

    /// no data yet
    public static string CardNoDataYet => Get("CardNoDataYet");

    /// as of {0}
    public static string CardLastSeen => Get("CardLastSeen");

    /// updated {0}
    public static string CardUpdated => Get("CardUpdated");

    /// Open Claude Code. Limits show up after its first answer.
    public static string CardNoDataNote => Get("CardNoDataNote");

    /// Aiko can't see the limits of this environment yet. You can turn on access in settings.
    public static string CardNoAccessNote => Get("CardNoAccessNote");

    /// {0}d {1}h
    public static string SpanDaysHours => Get("SpanDaysHours");

    /// {0}h {1}m
    public static string SpanHoursMinutes => Get("SpanHoursMinutes");

    /// {0}m
    public static string SpanMinutes => Get("SpanMinutes");

    /// &lt;1m
    public static string SpanUnderMinute => Get("SpanUnderMinute");

    /// open Claude Code
    public static string TrayOpenClaudeCode => Get("TrayOpenClaudeCode");

    /// as of {0}
    public static string TrayLastSeen => Get("TrayLastSeen");

    /// Aiko {0} is out
    public static string TrayUpdateOut => Get("TrayUpdateOut");

    /// Show {0} in the ring
    public static string MenuShowInRing => Get("MenuShowInRing");

    /// Refresh limits
    public static string MenuRefresh => Get("MenuRefresh");

    /// Settings
    public static string Settings => Get("Settings");

    /// Close
    public static string Close => Get("Close");

    /// Quit Aiko
    public static string QuitAiko => Get("QuitAiko");

    /// Check for updates
    public static string CheckForUpdates => Get("CheckForUpdates");

    /// Check for updates
    public static string CheckUpdatesToggle => Get("CheckUpdatesToggle");

    /// ENVIRONMENTS
    public static string SectionEnvironments => Get("SectionEnvironments");

    /// WHERE TO SHOW
    public static string SectionWhereToShow => Get("SectionWhereToShow");

    /// STARTUP AND UPDATES
    public static string SectionStartupAndUpdates => Get("SectionStartupAndUpdates");

    /// LANGUAGE
    public static string SectionLanguage => Get("SectionLanguage");

    /// Direct mode
    public static string DirectMode => Get("DirectMode");

    /// In direct mode, Aiko asks Anthropic for your limits itself. It uses the token Claude Code...
    public static string DirectModeWhat => Get("DirectModeWhat");

    /// If it's a work account, ask whoever manages it first.
    public static string DirectModeAsk => Get("DirectModeAsk");

    /// No environments yet. Aiko looks for them on the first run.
    public static string NoEnvironments => Get("NoEnvironments");

    /// Claude Code sends its limits to Aiko.
    public static string AccessOk => Get("AccessOk");

    /// One environment doesn't send its limits yet.
    public static string AccessMissingOne => Get("AccessMissingOne");

    /// {0} environments don't send their limits yet.
    public static string AccessMissingMany => Get("AccessMissingMany");

    /// Check access
    public static string AccessCheck => Get("AccessCheck");

    /// Set it up
    public static string AccessSetUp => Get("AccessSetUp");

    /// Aiko can't find its bridge program, so nothing changed.
    public static string AccessNoBridge => Get("AccessNoBridge");

    /// Tray
    public static string PlaceTray => Get("PlaceTray");

    /// Island
    public static string PlaceIsland => Get("PlaceIsland");

    /// Menu bar
    public static string PlaceMenuBar => Get("PlaceMenuBar");

    /// Hide the island in full screen
    public static string HideIslandInFullScreen => Get("HideIslandInFullScreen");

    /// Start with Windows
    public static string StartWithWindows => Get("StartWithWindows");

    /// Start at login
    public static string StartAtLogin => Get("StartAtLogin");

    /// Once a day Aiko asks slayumind.org for the latest version. The files come from GitHub, an...
    public static string CheckUpdatesWhat => Get("CheckUpdatesWhat");

    /// Check now
    public static string CheckNow => Get("CheckNow");

    /// Open download page
    public static string OpenDownloadPage => Get("OpenDownloadPage");

    /// Aiko is asking slayumind.org…
    public static string UpdateAsking => Get("UpdateAsking");

    /// Version {0} is available.
    public static string UpdateAvailable => Get("UpdateAvailable");

    /// Aiko {0} is the latest version.
    public static string UpdateLatest => Get("UpdateLatest");

    /// Couldn't check. Try again in a few minutes.
    public static string UpdateFailed => Get("UpdateFailed");

    /// Download and install
    public static string UpdateInstallNow => Get("UpdateInstallNow");

    /// Aiko is downloading {0}…
    public static string UpdateDownloading => Get("UpdateDownloading");

    /// Aiko {0} is ready. Restart to start using it.
    public static string UpdateReady => Get("UpdateReady");

    /// Restart now
    public static string UpdateRestartNow => Get("UpdateRestartNow");

    /// This copy wasn't put here by the installer, so Aiko can't replace it. Use the download page.
    public static string UpdateNotInstalled => Get("UpdateNotInstalled");

    /// The download didn't finish. Nothing was installed.
    public static string UpdateDownloadFailed => Get("UpdateDownloadFailed");

    /// This build has no update key yet, so it can't install updates. Use the download page.
    public static string UpdateNoKeyYet => Get("UpdateNoKeyYet");

    /// The release didn't pass the signature check. Nothing was installed.
    public static string UpdateBadSignature => Get("UpdateBadSignature");

    /// The downloaded file doesn't match the release list. Nothing was installed.
    public static string UpdateBadFile => Get("UpdateBadFile");

    /// System
    public static string LanguageSystem => Get("LanguageSystem");

    /// English
    public static string LanguageEnglish => Get("LanguageEnglish");

    /// Русский
    public static string LanguageRussian => Get("LanguageRussian");

    /// Copy diagnostics
    public static string CopyDiagnostics => Get("CopyDiagnostics");

    /// Aiko settings
    public static string SettingsWindowTitle => Get("SettingsWindowTitle");

    /// Environments
    public static string WizardStepEnvironments => Get("WizardStepEnvironments");

    /// Main
    public static string EnvironmentPlainName => Get("EnvironmentPlainName");

    /// Access to the limits
    public static string WizardStepAccess => Get("WizardStepAccess");

    /// Where to show Aiko
    public static string WizardStepWhere => Get("WizardStepWhere");

    /// step {0} of 3
    public static string WizardStepCount => Get("WizardStepCount");

    /// Back
    public static string Back => Get("Back");

    /// Not now
    public static string NotNow => Get("NotNow");

    /// Next
    public static string Next => Get("Next");

    /// Allow
    public static string Allow => Get("Allow");

    /// Finish
    public static string Finish => Get("Finish");

    /// Aiko found one Claude Code folder. That's enough to start, and you can add a second one l...
    public static string WizardFoundOne => Get("WizardFoundOne");

    /// Aiko found these Claude Code folders. Give them names you'll recognise and turn off the o...
    public static string WizardFoundMany => Get("WizardFoundMany");

    /// Aiko didn't find Claude Code on this computer. Install it and check again, or choose the ...
    public static string WizardNothingFound => Get("WizardNothingFound");

    /// Choose a folder
    public static string WizardChooseFolder => Get("WizardChooseFolder");

    /// Check again
    public static string WizardCheckAgain => Get("WizardCheckAgain");

    /// Choose a Claude Code folder
    public static string WizardFolderDialogTitle => Get("WizardFolderDialogTitle");

    /// Claude Code sends its limits to a status line. Aiko adds one line to the settings file of...
    public static string WizardAccessExplain => Get("WizardAccessExplain");

    /// THE LINE AIKO ADDS
    public static string WizardTheLine => Get("WizardTheLine");

    /// FILES AIKO CHANGES
    public static string WizardTheFiles => Get("WizardTheFiles");

    /// Aiko keeps a copy of each file next to it. Removing Aiko puts everything back.
    public static string WizardBackupNote => Get("WizardBackupNote");

    /// Aiko can't find its bridge program.
    public static string WizardBridgeNotFound => Get("WizardBridgeNotFound");

    /// Once a day, Aiko asks slayumind.org for the latest version and says that one copy of Aiko...
    public static string WizardUpdatesWhat => Get("WizardUpdatesWhat");

    /// Aiko is down by the clock. Rest the mouse on it to see the card, or click it to keep the ...
    public static string WizardDoneTray => Get("WizardDoneTray");

    /// Aiko is up by the clock. Rest the mouse on it to see the card, or click it to keep the ca...
    public static string WizardDoneMenuBar => Get("WizardDoneMenuBar");

    /// Aiko is at the top of your screen. Drag it anywhere and it sticks to the nearest edge.
    public static string WizardDoneIsland => Get("WizardDoneIsland");

    /// Windows 11 hides new app icons under the arrow next to the clock. Open the arrow and drag...
    public static string WizardDoneOverflow => Get("WizardDoneOverflow");

    /// A full menu bar hides the icons furthest from the clock. Close a menu bar app if Aiko doe...
    public static string WizardDoneMenuBarRoom => Get("WizardDoneMenuBarRoom");

    /// The first numbers arrive after your next answer from Claude Code. Until then, the ring is...
    public static string WizardDoneFirstNumbers => Get("WizardDoneFirstNumbers");

    /// Aiko can't see your limits yet. You can turn on access in settings at any time.
    public static string WizardDoneNoAccess => Get("WizardDoneNoAccess");

    /// Aiko couldn't write the Claude Code settings file. Try again.
    public static string SettingsWriteFailed => Get("SettingsWriteFailed");

    /// Aiko can't find its bridge program.
    public static string SettingsBridgeUnknown => Get("SettingsBridgeUnknown");

    /// Set up environments
    public static string ChecklistTitle => Get("ChecklistTitle");

    /// {0} of {1} done
    public static string ChecklistCount => Get("ChecklistCount");

    /// ENVIRONMENT 1
    public static string GroupFirst => Get("GroupFirst");

    /// ENVIRONMENT 2
    public static string GroupSecond => Get("GroupSecond");

    /// SHARED
    public static string GroupShared => Get("GroupShared");

    /// Install Claude Code
    public static string ItemInstall => Get("ItemInstall");

    /// Account
    public static string ItemAccount => Get("ItemAccount");

    /// Pick or create
    public static string ItemSecond => Get("ItemSecond");

    /// Launch commands
    public static string ItemCommands => Get("ItemCommands");

    /// Project folders
    public static string ItemFolders => Get("ItemFolders");

    /// installed
    public static string StateInstalled => Get("StateInstalled");

    /// waiting
    public static string StateWaiting => Get("StateWaiting");

    /// after install
    public static string StateAfterInstall => Get("StateAfterInstall");

    /// after sign-in
    public static string StateAfterSignIn => Get("StateAfterSignIn");

    /// after environment 2
    public static string StateAfterSecond => Get("StateAfterSecond");

    /// optional
    public static string StateOptional => Get("StateOptional");

    /// later
    public static string StateLater => Get("StateLater");

    /// connected
    public static string StateConnected => Get("StateConnected");

    /// sign in needed
    public static string StateSignInNeeded => Get("StateSignInNeeded");

    /// added
    public static string StateAdded => Get("StateAdded");

    /// none
    public static string StateNone => Get("StateNone");

    /// {0} bound
    public static string StateBound => Get("StateBound");

    /// tray
    public static string StateTray => Get("StateTray");

    /// island
    public static string StateIsland => Get("StateIsland");

    /// menu bar
    public static string StateMenuBar => Get("StateMenuBar");

    /// Copy
    public static string Copy => Get("Copy");

    /// Copied
    public static string Copied => Get("Copied");

    /// Later
    public static string Later => Get("Later");

    /// Claude Code is already on this computer. Nothing to do here.
    public static string InstallFound => Get("InstallFound");

    /// Claude Code isn't on this computer yet. Aiko works alongside it, so install it first.
    public static string InstallLead => Get("InstallLead");

    /// Open PowerShell, paste the command and press Enter. Aiko notices when it's done.
    public static string InstallHow => Get("InstallHow");

    /// Open Terminal, paste the command and press Enter. Aiko notices when it's done.
    public static string InstallHowMac => Get("InstallHowMac");

    /// Waiting for Claude Code…
    public static string WaitInstall => Get("WaitInstall");

    /// The first environment lives in the .claude folder. The Claude Code panel in VS Code and C...
    public static string Env1Lead => Get("Env1Lead");

    /// This folder has no account yet.
    public static string Env1Empty => Get("Env1Empty");

    /// This folder already has an account.
    public static string Env1Found => Get("Env1Found");

    /// Sign in
    public static string SignIn => Get("SignIn");

    /// Aiko opened Claude Code in a new window. Sign in there through your browser. Aiko waits a...
    public static string LoginHow => Get("LoginHow");

    /// Aiko never sees a password or a token, only that the account is connected.
    public static string LoginNever => Get("LoginNever");

    /// Waiting for you to sign in…
    public static string WaitLogin => Get("WaitLogin");

    /// NAME IN AIKO
    public static string NameInAiko => Get("NameInAiko");

    /// Account
    public static string AccountLabel => Get("AccountLabel");

    /// Plan
    public static string PlanLabel => Get("PlanLabel");

    /// Aiko found more Claude Code folders. Pick the one for your second environment, or create ...
    public static string Env2LeadFound => Get("Env2LeadFound");

    /// The second environment is a separate folder with its own account. Name it and Aiko create...
    public static string Env2LeadNew => Get("Env2LeadNew");

    /// One environment is enough to see limits. You can add the second one later in settings.
    public static string Env2Later => Get("Env2Later");

    /// Create a new one
    public static string CreateNew => Get("CreateNew");

    /// Create and sign in
    public static string CreateSignIn => Get("CreateSignIn");

    /// For example, Personal
    public static string NameExample => Get("NameExample");

    /// last session {0}
    public static string LastSession => Get("LastSession");

    /// Folder: {0}
    public static string FolderIs => Get("FolderIs");

    /// Add the line
    public static string AccessAdd => Get("AccessAdd");

    /// A command starts Claude Code in the right environment. It works in PowerShell, cmd and Gi...
    public static string CmdLead => Get("CmdLead");

    /// A command starts Claude Code in the right environment. It works in Terminal and in any zs...
    public static string CmdLeadMac => Get("CmdLeadMac");

    /// COMMAND · {0}
    public static string CmdFor => Get("CmdFor");

    /// Follows the environment name.
    public static string CmdFollows => Get("CmdFollows");

    /// Your own command: renaming doesn't change it.
    public static string CmdOwn => Get("CmdOwn");

    /// Use the name
    public static string CmdByName => Get("CmdByName");

    /// Enter a command.
    public static string CmdEmpty => Get("CmdEmpty");

    /// Up to 40 characters.
    public static string CmdTooLong => Get("CmdTooLong");

    /// Only a–z, 0–9, - and _.
    public static string CmdBadCharacters => Get("CmdBadCharacters");

    /// claude is the name of Claude Code itself.
    public static string CmdReserved => Get("CmdReserved");

    /// The other environment has this command.
    public static string CmdTaken => Get("CmdTaken");

    /// Your PowerShell profile has functions that switch accounts. They run before Aiko's comman...
    public static string FnsLead => Get("FnsLead");

    /// Remove {0}
    public static string FnRemove => Get("FnRemove");

    /// A copy of the profile stays next to it. Removing Aiko brings the functions back.
    public static string FnBackup => Get("FnBackup");

    /// Aiko puts its folder at the start of PATH so every terminal finds the commands. Restart o...
    public static string PathNote => Get("PathNote");

    /// THE LINE AIKO ADDS TO ~/.ZSHRC
    public static string PathLineMac => Get("PathLineMac");

    /// macOS puts a folder of your own on PATH only when your shell profile says so, so Aiko add...
    public static string PathNoteMac => Get("PathNoteMac");

    /// Add to PATH
    public static string PathAdd => Get("PathAdd");

    /// No commands
    public static string NoCommands => Get("NoCommands");

    /// Bind project folders to {0}. In them and in every folder inside, claude starts {0}.
    public static string FoldersLead => Get("FoldersLead");

    /// Add a project folder
    public static string AddProject => Get("AddProject");

    /// Choose a project folder
    public static string PickProject => Get("PickProject");

    /// Nothing is bound yet. You can do it later in settings.
    public static string NoBinds => Get("NoBinds");

    /// A command beats a binding: {0} in a bound folder starts {1}, and Claude Code reminds you ...
    public static string ExplicitWins => Get("ExplicitWins");

    /// Remove
    public static string Remove => Get("Remove");

    /// Commands: {0}. Open a new terminal to use them.
    public static string DoneCommands => Get("DoneCommands");

    /// Set up environments
    public static string SetUpEnvironments => Get("SetUpEnvironments");

    /// General
    public static string NavGeneral => Get("NavGeneral");

    /// {0} bound
    public static string NavBound => Get("NavBound");

    /// Add a second environment
    public static string AddSecondEnvironment => Get("AddSecondEnvironment");

    /// Saved
    public static string Saved => Get("Saved");

    /// default
    public static string ByDefault => Get("ByDefault");

    /// ACCOUNT
    public static string SectionAccount => Get("SectionAccount");

    /// Email
    public static string EmailLabel => Get("EmailLabel");

    /// Sign in again
    public static string SignInAgain => Get("SignInAgain");

    /// Claude Code opened in a new window.
    public static string ClaudeOpened => Get("ClaudeOpened");

    /// COMMAND
    public static string SectionCommand => Get("SectionCommand");

    /// PowerShell · cmd · Git Bash
    public static string CmdShells => Get("CmdShells");

    /// zsh · bash
    public static string CmdShellsMac => Get("CmdShellsMac");

    /// The command stays the same, since your terminals and scripts know it.
    public static string CmdKept => Get("CmdKept");

    /// Rename to {0}
    public static string RenameCommandTo => Get("RenameCommandTo");

    /// Enter a name.
    public static string NameEmpty => Get("NameEmpty");

    /// Up to 40 characters.
    public static string NameTooLong => Get("NameTooLong");

    /// The other environment has this name.
    public static string NameTaken => Get("NameTaken");

    /// BOUND FOLDERS
    public static string SectionBoundFolders => Get("SectionBoundFolders");

    /// No folders.
    public static string NoneBound => Get("NoneBound");

    /// And every other folder: this is the default environment.
    public static string RestToo => Get("RestToo");

    /// Change in project folders
    public static string EditInFolders => Get("EditInFolders");

    /// Remove environment
    public static string RemoveEnvironment => Get("RemoveEnvironment");

    /// Aiko's line and plugins leave this folder's settings.json, and so do the command {0} and ...
    public static string RemoveEnvironmentLine => Get("RemoveEnvironmentLine");

    /// And move the folder to the Recycle Bin
    public static string MoveToRecycleBin => Get("MoveToRecycleBin");

    /// And move the folder to the Trash
    public static string MoveToTrash => Get("MoveToTrash");

    /// It holds the Claude Code account, history and memory. You can restore it from the Recycle...
    public static string RecycleWhy => Get("RecycleWhy");

    /// It holds the Claude Code account, history and memory. You can put it back from the Trash.
    public static string TrashWhy => Get("TrashWhy");

    /// VS Code and Claude Desktop use the .claude folder, so Aiko never removes it.
    public static string KeepClaude => Get("KeepClaude");

    /// Cancel
    public static string Cancel => Get("Cancel");

    /// Remove
    public static string RemoveConfirm => Get("RemoveConfirm");

    /// {0} removed.
    public static string EnvironmentRemoved => Get("EnvironmentRemoved");

    /// {0} removed. The folder is in the Recycle Bin.
    public static string EnvironmentRemovedToBin => Get("EnvironmentRemovedToBin");

    /// {0} removed. The folder is in the Trash.
    public static string EnvironmentRemovedToTrash => Get("EnvironmentRemovedToTrash");

    /// In a folder and in every folder inside, plain claude starts its environment. A command li...
    public static string FoldersTableLead => Get("FoldersTableLead");

    /// FOLDER
    public static string FolderColumn => Get("FolderColumn");

    /// ENVIRONMENT
    public static string EnvironmentColumn => Get("EnvironmentColumn");

    /// All other folders
    public static string AllOtherFolders => Get("AllOtherFolders");

    /// Add a folder
    public static string AddFolder => Get("AddFolder");

    /// Remove binding
    public static string RemoveBinding => Get("RemoveBinding");

    /// Bindings matter once you have two environments. Right now every folder runs in {0}.
    public static string FoldersOneEnvironment => Get("FoldersOneEnvironment");

    /// Bindings work through the launch commands, and those aren't set up yet.
    public static string FoldersNeedCommands => Get("FoldersNeedCommands");

    /// ACCESS TO THE LIMITS
    public static string SectionAccess => Get("SectionAccess");

    /// DIAGNOSTICS
    public static string SectionDiagnostics => Get("SectionDiagnostics");

    /// Version and settings for a bug report. No tokens and no email addresses.
    public static string DiagnosticsWhat => Get("DiagnosticsWhat");

    /// Diagnostics copied.
    public static string DiagnosticsCopied => Get("DiagnosticsCopied");

    /// Environments are set up.
    public static string SetupDone => Get("SetupDone");

    /// Start over
    public static string Restart => Get("Restart");

    /// Removes the environments from Aiko and opens the checklist right here.
    public static string RestartWhat => Get("RestartWhat");

    /// Aiko removes the environments, its lines and plugins in settings.json, the commands {0}, ...
    public static string RestartLine => Get("RestartLine");

    /// Aiko removes the environments, its lines and plugins in settings.json, the commands {0}, ...
    public static string RestartLineMac => Get("RestartLineMac");

    /// And move {0} to the Recycle Bin
    public static string RestartBin => Get("RestartBin");

    /// And move {0} to the Trash
    public static string RestartTrash => Get("RestartTrash");

    /// .claude stays either way.
    public static string RestartKeep => Get("RestartKeep");

    /// Open Claude Code
    public static string OpenClaudeCode => Get("OpenClaudeCode");

    /// Sign in so Aiko can see the limits of this environment.
    public static string CardSignInNote => Get("CardSignInNote");

    /// working now
    public static string StateWorkingNow => Get("StateWorkingNow");

    /// Personality
    public static string NavPersonality => Get("NavPersonality");

    /// on: {0}
    public static string NavPersonaOn => Get("NavPersonaOn");

    /// off
    public static string NavPersonaOff => Get("NavPersonaOff");

    /// Privacy
    public static string NavPrivacy => Get("NavPrivacy");

    /// statistics: on
    public static string NavPrivacyStatsOn => Get("NavPrivacyStatsOn");

    /// statistics: off
    public static string NavPrivacyStatsOff => Get("NavPrivacyStatsOff");

    /// CONNECTION TO SLAYUMIND.ORG
    public static string SectionConnection => Get("SectionConnection");

    /// Send anonymous statistics
    public static string SendStatsToggle => Get("SendStatsToggle");

    /// The same request says that one copy ran today. The author of Aiko sees numbers and nothin...
    public static string SendStatsWhat => Get("SendStatsWhat");

    /// WHAT IS SENT
    public static string SectionWhatIsSent => Get("SectionWhatIsSent");

    /// the version of Aiko: whether updates arrive
    public static string SentVersion => Get("SentVersion");

    /// the version of Windows: what to test first
    public static string SentWindows => Get("SentWindows");

    /// the version of macOS: what to test first
    public static string SentMacOS => Get("SentMacOS");

    /// an ID that changes every day
    public static string SentDayId => Get("SentDayId");

    /// the first run this week
    public static string SentWeekFlag => Get("SentWeekFlag");

    /// the first run this month
    public static string SentMonthFlag => Get("SentMonthFlag");

    /// the personality is on in at least one environment
    public static string SentPersona => Get("SentPersona");

    /// None of this is sent right now.
    public static string NothingSentYet => Get("NothingSentYet");

    /// WHAT NEVER LEAVES
    public static string SectionNeverSent => Get("SectionNeverSent");

    /// Your name, email, project folders, limits, token and session texts. The site doesn't read...
    public static string NeverSentWhat => Get("NeverSentWhat");

    /// The rows are deleted after 90 days.
    public static string StatsKeptFor => Get("StatsKeptFor");

    /// Reset ID
    public static string ResetInstallId => Get("ResetInstallId");

    /// Aiko makes a new value, and the days before it can't be linked to it.
    public static string ResetInstallIdWhat => Get("ResetInstallIdWhat");

    /// The ID is new.
    public static string ResetInstallIdDone => Get("ResetInstallIdDone");

    /// Open PRIVACY.md
    public static string OpenPrivacyDoc => Get("OpenPrivacyDoc");

    /// What Aiko sends and to whom — Privacy.
    public static string PrivacyLinkFromGeneral => Get("PrivacyLinkFromGeneral");

    /// Anonymous statistics
    public static string WizardStats => Get("WizardStats");

    /// The author of Aiko doesn't know how many people use it. Once a day Aiko can say that one ...
    public static string WizardStatsWhat => Get("WizardStatsWhat");

    /// You can change this later in settings, under Privacy.
    public static string WizardStatsLater => Get("WizardStatsLater");

    /// Don't send
    public static string StatsDecline => Get("StatsDecline");

    /// Send
    public static string StatsAccept => Get("StatsAccept");

    /// on
    public static string StatsStateOn => Get("StatsStateOn");

    /// off
    public static string StatsStateOff => Get("StatsStateOff");

    /// not chosen
    public static string StatsStateUnset => Get("StatsStateUnset");

    /// WHERE AIKO TALKS
    public static string SectionWhereAikoTalks => Get("SectionWhereAikoTalks");

    /// Works in new sessions. Open sessions finish the way they started.
    public static string PersonaNewSessions => Get("PersonaNewSessions");

    /// While the personality is on, your style {0} doesn't work. Turn it off and it comes back.
    public static string PersonaOwnStyle => Get("PersonaOwnStyle");

    /// FACE
    public static string SectionFace => Get("SectionFace");

    /// Chibi
    public static string FaceChibi => Get("FaceChibi");

    /// Emoji
    public static string FaceEmoji => Get("FaceEmoji");

    /// This is how Aiko looks in the tray, on the island and in windows.
    public static string FaceWhere => Get("FaceWhere");

    /// That's how Aiko looks in the menu bar, on the island and in the windows.
    public static string FaceWhereMac => Get("FaceWhereMac");

    /// TEMPERAMENT
    public static string SectionTemperament => Get("SectionTemperament");

    /// Quiet
    public static string TemperamentQuiet => Get("TemperamentQuiet");

    /// Normal
    public static string TemperamentNormal => Get("TemperamentNormal");

    /// Bright
    public static string TemperamentBright => Get("TemperamentBright");

    /// Almost no character: one warm line at the end of an answer.
    public static string TemperamentQuietAbout => Get("TemperamentQuietAbout");

    /// A short interjection at the start, a quick verdict at the end. Japanese words now and then.
    public static string TemperamentNormalAbout => Get("TemperamentNormalAbout");

    /// An interjection in every answer, game metaphors, Japanese words more often.
    public static string TemperamentBrightAbout => Get("TemperamentBrightAbout");

    /// Everything at full. In code, commits, files and errors she still stays quiet.
    public static string TemperamentMusouAbout => Get("TemperamentMusouAbout");

    /// HOW SHE'LL ANSWER
    public static string SectionSampleReply => Get("SectionSampleReply");

    /// Why does the reset countdown show 0 minutes?
    public static string SampleQuestion => Get("SampleQuestion");

    /// The limits test passed by luck: rounding went down, so a reset at 14:59:30 showed as “in ...
    public static string SampleBody => Get("SampleBody");

    /// The limits test passed by luck: rounding went down, so a reset at 14:59:30 hid behind “in...
    public static string SampleBodyBright => Get("SampleBodyBright");

    ///  Parried it, like in Elden Ring.
    public static string SampleBodyMusouTail => Get("SampleBodyMusouTail");

    /// えへへ, got it.
    public static string SampleOpenNormal => Get("SampleOpenNormal");

    /// やった, got it!
    public static string SampleOpenBright => Get("SampleOpenBright");

    /// やった〜! すごい, what a sneaky one!
    public static string SampleOpenMusou => Get("SampleOpenMusou");

    /// A rare bug. It was nice to find.
    public static string SampleCloseQuiet => Get("SampleCloseQuiet");

    /// In my own game I'd have hunted a bug like this for half a day.
    public static string SampleCloseNormal => Get("SampleCloseNormal");

    /// お疲れ様!
    public static string SampleCloseBright => Get("SampleCloseBright");

    /// よし、行くぞ! On to the next one (^_^)
    public static string SampleCloseMusou => Get("SampleCloseMusou");

    /// The commit for this fix has no character:
    public static string SampleCommit => Get("SampleCommit");

    /// SKILLS · {0}
    public static string SectionSkills => Get("SectionSkills");

    /// Skills work in environments where the personality is on.
    public static string SkillsWork => Get("SkillsWork");

    /// Aiko's skills
    public static string SkillsSwitch => Get("SkillsSwitch");

    /// Turn the personality on in at least one environment, and the skills start working.
    public static string SkillsNeedPersona => Get("SkillsNeedPersona");

    /// PROJECT MANAGEMENT
    public static string SkillDomainProjects => Get("SkillDomainProjects");

    /// GAME DEVELOPMENT
    public static string SkillDomainGames => Get("SkillDomainGames");

    /// UI text, READMEs and release notes without stiff wording or AI tells. RU and EN.
    public static string SkillAikoCopy => Get("SkillAikoCopy");

    /// Before a release: what can't be undone, how to roll back, whether the docs match the code.
    public static string SkillAikoReleaseGate => Get("SkillAikoReleaseGate");

    /// One fact in one place, a decision log, contradictions found.
    public static string SkillAikoDocsHygiene => Get("SkillAikoDocsHygiene");

    /// Checks a game with numbers: the same test scene before and after a change.
    public static string SkillAikoPlaytest => Get("SkillAikoPlaytest");

    /// A model from Blender to Unity: axes, normals, export and import.
    public static string SkillAikoBlenderToUnity => Get("SkillAikoBlenderToUnity");

    /// Ready files for textures: a size that fits the camera, and sheets to paint over.
    public static string SkillAikoTexturing => Get("SkillAikoTexturing");

    /// A .glb for the web: size, axes, compression, a blank view where the model should be.
    public static string SkillAikoGlbForWeb => Get("SkillAikoGlbForWeb");

    /// Fit a color to the palette in OKLCH with the smallest change.
    public static string SkillAikoPalette => Get("SkillAikoPalette");

    /// 30–40 games with the mechanic you need: an overview with screenshots, and interactive dem...
    public static string SkillAikoGamedesignResearch => Get("SkillAikoGamedesignResearch");

    /// Plan the day in Google Calendar, find free time, add events after your yes.
    public static string SkillAikoCalendar => Get("SkillAikoCalendar");

    /// Documents from Google Drive into the work, and files from the project onto Drive.
    public static string SkillAikoDrive => Get("SkillAikoDrive");

    /// Meet Aiko
    public static string ItemMeetAiko => Get("ItemMeetAiko");

    /// Aiko can talk in your Claude Code sessions in her own voice, and she brings eleven skills...
    public static string MeetAikoLead => Get("MeetAikoLead");

    /// The temperament, the face and the skills are in settings, under Personality. It works in ...
    public static string MeetAikoSettings => Get("MeetAikoSettings");

    /// Turn on in {0}
    public static string MeetAikoTurnOn => Get("MeetAikoTurnOn");

    /// on
    public static string StateOn => Get("StateOn");
}
