// <auto-generated>
//     Made by tools/strings.py from tools/strings.json. Do not edit by hand: run the script.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace Aiko.App;

/// Every word Aiko says, in the language the user chose. One property per string, so a key that
/// does not exist is a build error and not a blank label somebody finds months later.
public static class Strings
{
    private static readonly ResourceManager Resources =
        new("Aiko.App.Strings", typeof(Strings).Assembly);

    /// Set at startup and again when the language changes.
    public static CultureInfo? Culture { get; set; }

    private static string Get(string key) => Resources.GetString(key, Culture) ?? key;

    /// Session · 5 hours
    public static string CardSession => Get("CardSession");

    /// Week
    public static string CardWeek => Get("CardWeek");

    /// {0} · week
    public static string CardModelWeek => Get("CardModelWeek");

    /// {0}% used
    public static string CardPercentUsed => Get("CardPercentUsed");

    /// resets in {0}
    public static string CardResets => Get("CardResets");

    /// just reset
    public static string CardJustReset => Get("CardJustReset");

    /// lasts until reset
    public static string CardLastsUntilReset => Get("CardLastsUntilReset");

    /// ~{0} at this pace
    public static string CardAtThisPace => Get("CardAtThisPace");

    /// running low
    public static string CardToneCaution => Get("CardToneCaution");

    /// almost gone
    public static string CardToneCritical => Get("CardToneCritical");

    /// no data yet
    public static string CardNoDataYet => Get("CardNoDataYet");

    /// as of {0}
    public static string CardLastSeen => Get("CardLastSeen");

    /// updated {0}
    public static string CardUpdated => Get("CardUpdated");

    /// Open Claude Code. Limits show up after its first answer.
    public static string CardNoDataNote => Get("CardNoDataNote");

    /// Aiko can't see the limits of this environment yet. You can turn on access in settings.
    public static string CardNoAccessNote => Get("CardNoAccessNote");

    /// {0}d {1}h
    public static string SpanDaysHours => Get("SpanDaysHours");

    /// {0}h {1}m
    public static string SpanHoursMinutes => Get("SpanHoursMinutes");

    /// {0}m
    public static string SpanMinutes => Get("SpanMinutes");

    /// &lt;1m
    public static string SpanUnderMinute => Get("SpanUnderMinute");

    /// open Claude Code
    public static string TrayOpenClaudeCode => Get("TrayOpenClaudeCode");

    /// as of {0}
    public static string TrayLastSeen => Get("TrayLastSeen");

    /// Aiko {0} is out
    public static string TrayUpdateOut => Get("TrayUpdateOut");

    /// Show {0} in the ring
    public static string MenuShowInRing => Get("MenuShowInRing");

    /// Refresh limits
    public static string MenuRefresh => Get("MenuRefresh");

    /// Settings
    public static string Settings => Get("Settings");

    /// Close
    public static string Close => Get("Close");

    /// Quit Aiko
    public static string QuitAiko => Get("QuitAiko");

    /// Check for updates
    public static string CheckForUpdates => Get("CheckForUpdates");

    /// Check for updates
    public static string CheckUpdatesToggle => Get("CheckUpdatesToggle");

    /// ENVIRONMENTS
    public static string SectionEnvironments => Get("SectionEnvironments");

    /// WHERE TO SHOW
    public static string SectionWhereToShow => Get("SectionWhereToShow");

    /// STARTUP AND UPDATES
    public static string SectionStartupAndUpdates => Get("SectionStartupAndUpdates");

    /// LANGUAGE
    public static string SectionLanguage => Get("SectionLanguage");

    /// Direct mode
    public static string DirectMode => Get("DirectMode");

    /// In direct mode, Aiko asks Anthropic for your limits itself. It uses the token Claude Code...
    public static string DirectModeWhat => Get("DirectModeWhat");

    /// If it's a work account, ask whoever manages it first.
    public static string DirectModeAsk => Get("DirectModeAsk");

    /// No environments yet. Aiko looks for them on the first run.
    public static string NoEnvironments => Get("NoEnvironments");

    /// Claude Code sends its limits to Aiko.
    public static string AccessOk => Get("AccessOk");

    /// One environment doesn't send its limits yet.
    public static string AccessMissingOne => Get("AccessMissingOne");

    /// {0} environments don't send their limits yet.
    public static string AccessMissingMany => Get("AccessMissingMany");

    /// Check access
    public static string AccessCheck => Get("AccessCheck");

    /// Set it up
    public static string AccessSetUp => Get("AccessSetUp");

    /// Aiko can't find its bridge program, so nothing changed.
    public static string AccessNoBridge => Get("AccessNoBridge");

    /// Tray
    public static string PlaceTray => Get("PlaceTray");

    /// Island
    public static string PlaceIsland => Get("PlaceIsland");

    /// Hide the island in full screen
    public static string HideIslandInFullScreen => Get("HideIslandInFullScreen");

    /// Start with Windows
    public static string StartWithWindows => Get("StartWithWindows");

    /// Once a day, Aiko asks slayumind.org for the latest version and says that one copy of Aiko...
    public static string CheckUpdatesWhat => Get("CheckUpdatesWhat");

    /// Check now
    public static string CheckNow => Get("CheckNow");

    /// Open download page
    public static string OpenDownloadPage => Get("OpenDownloadPage");

    /// Aiko is asking slayumind.org…
    public static string UpdateAsking => Get("UpdateAsking");

    /// Version {0} is available.
    public static string UpdateAvailable => Get("UpdateAvailable");

    /// Aiko {0} is the latest version.
    public static string UpdateLatest => Get("UpdateLatest");

    /// Couldn't check. Try again in a few minutes.
    public static string UpdateFailed => Get("UpdateFailed");

    /// System
    public static string LanguageSystem => Get("LanguageSystem");

    /// English
    public static string LanguageEnglish => Get("LanguageEnglish");

    /// Русский
    public static string LanguageRussian => Get("LanguageRussian");

    /// Copy diagnostics
    public static string CopyDiagnostics => Get("CopyDiagnostics");

    /// Welcome to Aiko
    public static string WizardWindowTitle => Get("WizardWindowTitle");

    /// Aiko settings
    public static string SettingsWindowTitle => Get("SettingsWindowTitle");

    /// Environments
    public static string WizardStepEnvironments => Get("WizardStepEnvironments");

    /// Main
    public static string EnvironmentPlainName => Get("EnvironmentPlainName");

    /// Access to the limits
    public static string WizardStepAccess => Get("WizardStepAccess");

    /// Where to show Aiko
    public static string WizardStepWhere => Get("WizardStepWhere");

    /// All set
    public static string WizardStepDone => Get("WizardStepDone");

    /// step {0} of 3
    public static string WizardStepCount => Get("WizardStepCount");

    /// Back
    public static string Back => Get("Back");

    /// Not now
    public static string NotNow => Get("NotNow");

    /// Next
    public static string Next => Get("Next");

    /// Allow
    public static string Allow => Get("Allow");

    /// Finish
    public static string Finish => Get("Finish");

    /// Aiko found one Claude Code folder. That's enough to start, and you can add a second one l...
    public static string WizardFoundOne => Get("WizardFoundOne");

    /// Aiko found these Claude Code folders. Give them names you'll recognise and turn off the o...
    public static string WizardFoundMany => Get("WizardFoundMany");

    /// Aiko didn't find Claude Code on this computer. Install it and check again, or choose the ...
    public static string WizardNothingFound => Get("WizardNothingFound");

    /// Choose a folder
    public static string WizardChooseFolder => Get("WizardChooseFolder");

    /// Check again
    public static string WizardCheckAgain => Get("WizardCheckAgain");

    /// Choose a Claude Code folder
    public static string WizardFolderDialogTitle => Get("WizardFolderDialogTitle");

    /// Claude Code sends its limits to a status line. Aiko adds one line to the settings file of...
    public static string WizardAccessExplain => Get("WizardAccessExplain");

    /// THE LINE AIKO ADDS
    public static string WizardTheLine => Get("WizardTheLine");

    /// FILES AIKO CHANGES
    public static string WizardTheFiles => Get("WizardTheFiles");

    /// Aiko keeps a copy of each file next to it. Removing Aiko puts everything back.
    public static string WizardBackupNote => Get("WizardBackupNote");

    /// Aiko can't find its bridge program.
    public static string WizardBridgeNotFound => Get("WizardBridgeNotFound");

    /// Once a day, Aiko asks slayumind.org for the latest version and says that one copy of Aiko...
    public static string WizardUpdatesWhat => Get("WizardUpdatesWhat");

    /// Aiko is down by the clock. Rest the mouse on it to see the card, or click it to keep the ...
    public static string WizardDoneTray => Get("WizardDoneTray");

    /// Aiko is at the top of your screen. Drag it anywhere and it sticks to the nearest edge.
    public static string WizardDoneIsland => Get("WizardDoneIsland");

    /// Windows 11 hides new app icons under the arrow next to the clock. Open the arrow and drag...
    public static string WizardDoneOverflow => Get("WizardDoneOverflow");

    /// The first numbers arrive after your next answer from Claude Code. Until then, the ring is...
    public static string WizardDoneFirstNumbers => Get("WizardDoneFirstNumbers");

    /// Aiko can't see your limits yet. You can turn on access in settings at any time.
    public static string WizardDoneNoAccess => Get("WizardDoneNoAccess");

    /// Aiko couldn't write the Claude Code settings file. Try again.
    public static string SettingsWriteFailed => Get("SettingsWriteFailed");

    /// Aiko can't find its bridge program.
    public static string SettingsBridgeUnknown => Get("SettingsBridgeUnknown");
}
